apiVersion: v1
kind: Service
metadata:
  name: {{ include "docker-like-name-generator.fullname" . }}
  labels:
    {{- include "docker-like-name-generator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      {{- if .Values.service }}
      {{- if eq .Values.service.type "NodePort"}}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
      {{- end }}
      protocol: TCP
      name: http
  selector:
    {{- include "docker-like-name-generator.selectorLabels" . | nindent 4 }}